FROM python:3.11-slim

WORKDIR /app

COPY requirements_mlops.txt .
RUN pip install --no-cache-dir -r requirements_mlops.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app_fastapi:app", "--host", "0.0.0.0", "--port", "8000"]
